import { useEffect, useRef, useState } from 'react'
import { post, request } from './api'
import type { ResearchObject, Snapshot } from './api'
import { kindLabels, MathInputHint, MathPreview, Modal } from './ui'
import { defaultRunOptions, RunOptionsFields } from './RunOptions'

export interface ProviderStatus { provider:string;configured:boolean;enabled:boolean;available?:boolean }
export function ActionDialog({action,snapshot:liveSnapshot,selected:liveSelected,providers,onClose,onComplete}:{action:string;snapshot:Snapshot|null;selected:ResearchObject|null;providers:ProviderStatus[];onClose:()=>void;onComplete:(result?:{project_id?:string;branch_id?:string;object_id?:string},message?:string)=>Promise<void>}){
  const [snapshot]=useState(liveSnapshot),[selected]=useState(liveSelected)
  const branchProgress=useRef<{branch_id?:string;object_id?:string}>({})
  const [runtimeSettings,setRuntimeSettings]=useState<{allow_real_api:boolean;allowed_providers:string[]}|null>(null)
  useEffect(()=>{if(snapshot&&['run','review-run'].includes(action))request<{allow_real_api:boolean;allowed_providers:string[]}>(`/projects/${snapshot.project.id}/runtime-settings`).then(setRuntimeSettings).catch(()=>undefined)},[snapshot?.project.id,action])
  const [title,setTitle]=useState(''),[body,setBody]=useState(''),[kind,setKind]=useState('claim'),[role,setRole]=useState('assumption'),[outcome,setOutcome]=useState('unresolved'),[premises,setPremises]=useState<string[]>([]),[contexts,setContexts]=useState<string[]>([]),[assumptions,setAssumptions]=useState<string[]>([]),[gaps,setGaps]=useState(''),[scope,setScope]=useState(''),[verdict,setVerdict]=useState('inconclusive'),[coverage,setCoverage]=useState('partial'),[provider,setProvider]=useState('fake'),[budget,setBudget]=useState(8),[quote,setQuote]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  const [runOptions,setRunOptions]=useState({...defaultRunOptions,autonomous:action!=='review-run'})
  const [targetRevision,setTargetRevision]=useState(selected?.revision.id||snapshot?.objects.find(o=>o.id===snapshot.project.original_goal_id)?.revision.id||'')
  const [evidence,setEvidence]=useState<string[]>([]),[evidenceExplanation,setEvidenceExplanation]=useState(''),[retryConditions,setRetryConditions]=useState('')
  const [authors,setAuthors]=useState(''),[sourceId,setSourceId]=useState(''),[locator,setLocator]=useState(''),[accessedOn,setAccessedOn]=useState(new Date().toLocaleDateString('en-CA')),[verification,setVerification]=useState('provided')
  const titles:Record<string,string>={project:'新建研究',object:'新增研究对象',proof:'添加证明方案',review:'记录人工审查',annotation:'添加版本批注',branch:'创建研究分支',run:'从此处继续研究','review-run':'请求独立审查',block:'添加工作稿笔记',failure:'记录尝试与失败',source:'手工录入来源'}
  const list=snapshot?.objects||[]
  const toggle=(values:string[],id:string,set:(next:string[])=>void)=>set(values.includes(id)?values.filter(value=>value!==id):[...values,id])
  async function submit(event:React.FormEvent){event.preventDefault();setBusy(true);setError('');try{
    let result:{project_id?:string;branch_id?:string;object_id?:string}|undefined
    const branch_id=snapshot?.branch.id
    if(action==='project')result=await post('/projects',{title,body})
    else if(action==='object'){result=await post('/objects',{branch_id,kind,body,payload:kind==='context'?{role}:{}})}
    else if(action==='failure'){result=await post('/failures',{branch_id,target_revision_id:targetRevision,outcome,body,assumption_revision_ids:assumptions,evidence_revision_ids:evidence,scope,evidence_explanation:evidenceExplanation,retry_conditions:retryConditions.split('\n').map(s=>s.trim()).filter(Boolean)})}
    else if(action==='source'){result=await post('/sources',{branch_id,title,body,authors:authors.split('\n').map(s=>s.trim()).filter(Boolean),url_or_identifier:sourceId,locator,accessed_on:accessedOn,verification})}
    else if(action==='proof'){if(!selected)throw new Error('请先选择命题。');result=await post('/proof-plans',{branch_id,conclusion_revision_id:selected.revision.id,body,premise_revision_ids:premises,context_revision_ids:contexts,assumption_revision_ids:assumptions,gaps:gaps.split('\n').filter(s=>s.trim()),rule:'direct'})}
    else if(action==='review'){if(!selected)throw new Error('请先选择对象。');await post('/reviews',{branch_id,target_revision_id:selected.revision.id,kind:'human_review',verdict,coverage,scope,findings:body.split('\n').filter(s=>s.trim())})}
    else if(action==='annotation'){if(!selected)throw new Error('请先选择对象。');await post('/annotations',{branch_id,revision_id:selected.revision.id,body,anchor_quote:quote.trim()||null})}
    else if(action==='branch'){
      if(!branchProgress.current.branch_id){const created=await post<{branch_id:string}>('/branches',{source_branch_id:branch_id,name:title});branchProgress.current.branch_id=created.branch_id}
      const created=branchProgress.current
      if(body.trim()){
        if(!created.object_id){const goal=await post<{object_id:string}>('/objects',{branch_id:created.branch_id,kind:'problem',body,payload:{derived_from:selected?.id||snapshot?.project.original_goal_id}});created.object_id=goal.object_id}
        await post('/relations',{branch_id:created.branch_id,source_id:selected?.id||snapshot?.project.original_goal_id,target_id:created.object_id,kind:'rewrites'})
      }
      result={...created}
    }
    else if(action==='run'||action==='review-run'){await post('/runs',{branch_id,goal_object_id:selected?.id||snapshot?.project.original_goal_id,instruction:body,provider,mode:action==='review-run'?'review':'research',...runOptions,request_budget:budget})}
    else if(action==='block')await post('/manuscript/blocks',{branch_id,kind:'text',body})
    await onComplete(result,action==='run'||action==='review-run'?'任务已排队，运行面板会显示实际进度。':'已保存到当前研究空间。');onClose()
  }catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <Modal title={titles[action]||'研究操作'} onClose={onClose}><form onSubmit={submit}>{error&&<p className="inline-error" role="alert">{error}</p>}
    {selected&&['proof','review','annotation','run','review-run'].includes(action)&&<div className="selected-context"><span>{action==='run'||action==='review-run'?'执行时读取此对象的最新版本；实际输入见运行记录':`作用于选定版本 · ${selected.revision.id.slice(0,8)}`}</span><MathPreview body={selected.revision.body}/></div>}
    {(action==='project'||action==='branch')&&<label className="field-label">{action==='project'?'项目名称':'分支名称'}<input autoFocus value={title} onChange={e=>setTitle(e.target.value)} required maxLength={120} placeholder={action==='project'?'例如：解析矩阵族的特征值':'例如：加入谱隙条件'}/></label>}
    {action==='object'&&<label className="field-label">对象类型<select value={kind} onChange={e=>setKind(e.target.value)}>{Object.entries(kindLabels).filter(([key])=>key!=='activity'&&key!=='argument').map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label>}
    {action==='object'&&kind==='context'&&<label className="field-label">上下文类型<select value={role} onChange={e=>setRole(e.target.value)}><option value="assumption">假设（保持条件标记）</option><option value="definition">定义</option><option value="convention">符号约定</option></select></label>}
    {action==='failure'&&<><label className="field-label">本次尝试的目标版本<select required value={targetRevision} onChange={e=>setTargetRevision(e.target.value)}>{list.map((o,index)=><option key={o.revision.id} value={o.revision.id}>{kindLabels[o.kind]} {index+1} · {o.revision.id.slice(0,8)}</option>)}</select></label><MathPreview body={list.find(o=>o.revision.id===targetRevision)?.revision.body||''}/><label className="field-label">本次尝试的结果<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="unresolved">暂未解决</option><option value="argument_error">具体论证错误</option><option value="method_obstruction">有证据的方法障碍</option><option value="refuted">命题被反驳</option></select></label><p className="subtle">记录只适用于选定目标、前提与证据范围，不自动推断其他方法不可行。</p></>}
    {action==='source'&&<><label className="field-label">来源题名<input required value={title} onChange={e=>setTitle(e.target.value)} maxLength={500}/></label><label className="field-label">作者（每行一位，可留空）<textarea rows={2} value={authors} onChange={e=>setAuthors(e.target.value)}/></label><label className="field-label">链接或文献标识<input required value={sourceId} onChange={e=>setSourceId(e.target.value)} placeholder="DOI、ISBN、URL 或馆藏编号"/></label><div className="form-grid"><label className="field-label">来源定位<input required value={locator} onChange={e=>setLocator(e.target.value)} placeholder="页码、定理编号或章节"/></label><label className="field-label">访问日期<input type="date" required value={accessedOn} onChange={e=>setAccessedOn(e.target.value)}/></label></div><label className="field-label">来源核对状态<select value={verification} onChange={e=>setVerification(e.target.value)}><option value="provided">已提供原始来源材料</option><option value="unverified">来源待核对（例如模型记忆）</option></select></label><p className="subtle">录入来源信息会保存到本机；系统不会自动打开链接或下载材料。</p></>}
    {action==='review'&&<div className="form-grid"><label className="field-label">审查结论<select value={verdict} onChange={e=>setVerdict(e.target.value)}><option value="inconclusive">仍未确定</option><option value="issues">发现具体问题</option><option value="passed">未发现问题</option></select></label><label className="field-label">覆盖范围<select value={coverage} onChange={e=>setCoverage(e.target.value)}><option value="partial">局部步骤</option><option value="whole_plan">整份论证</option></select></label></div>}
    {(action==='review'||action==='failure')&&<label className="field-label">{action==='review'?'具体检查范围':'证据与适用范围'}<input value={scope} onChange={e=>setScope(e.target.value)} required placeholder="例如：只检查了 t=0 处左右导数的精确计算"/></label>}
    {action==='annotation'&&<label className="field-label">引用原文（可选）<textarea rows={2} value={quote} onChange={e=>setQuote(e.target.value)} placeholder="粘贴当前版本中的一句话，定位批注"/></label>}
    {(action==='run'||action==='review-run')&&<div className="form-grid"><label className="field-label">执行后端<select value={provider} onChange={e=>setProvider(e.target.value)}><option value="fake">模拟执行 · 不调用真实模型</option>{['deepseek','glm'].map(name=>{const p=providers.find(v=>v.provider===name);return <option key={name} value={name} disabled={!p?.enabled||!p?.configured||!runtimeSettings?.allow_real_api||!runtimeSettings.allowed_providers.includes(name)}>{name==='glm'?'GLM':'DeepSeek'}{p?.enabled&&p.configured&&runtimeSettings?.allow_real_api&&runtimeSettings.allowed_providers.includes(name)?'':' · 尚未启用'}</option>})}</select></label><label className="field-label">{runOptions.autonomous?'整题累计请求上限':'本任务请求上限'}<input type="number" min={1} max={1000} value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label></div>}
    {(action==='run'||action==='review-run')&&<RunOptionsFields value={{...runOptions,request_budget:budget}} onChange={next=>{setRunOptions(next);setBudget(next.request_budget)}} showBudget={false}/>}
    <label className="field-label">{({project:'最初的问题',branch:'衍生问题（可选，原问题仍保留）',proof:'完整论证或当前证明草稿',review:'具体审查意见（每行一项）',annotation:'批注内容',run:'研究指令','review-run':'希望重点检查什么',failure:'目标、尝试过程与失败位置',source:'来源材料与摘录',block:'工作稿笔记'} as Record<string,string>)[action]||'正文'}<textarea autoFocus={!['project','branch','source'].includes(action)} rows={6} value={body} onChange={e=>setBody(e.target.value)} required={!['branch','run','review-run'].includes(action)} placeholder={action==='project'?'写下一个问题、猜想或尚未完成的证明…':'支持 Markdown 与 $LaTeX$ 公式'}/></label>
    {action==='failure'&&<><fieldset className="choice-list"><legend>本次使用的前提版本</legend>{list.filter(o=>o.kind==='context'||o.kind==='claim').map(o=><label key={o.id}><input type="checkbox" checked={assumptions.includes(o.revision.id)} onChange={()=>toggle(assumptions,o.revision.id,setAssumptions)}/><span><MathPreview body={o.revision.body}/><code>{o.revision.id.slice(0,8)}</code></span></label>)}</fieldset><fieldset className="choice-list"><legend>支持本记录的证据版本</legend>{list.filter(o=>o.revision.id!==targetRevision).map(o=><label key={o.id}><input type="checkbox" checked={evidence.includes(o.revision.id)} onChange={()=>toggle(evidence,o.revision.id,setEvidence)}/><MathPreview body={o.revision.body}/></label>)}</fieldset><label className="field-label">证据说明<textarea required={outcome!=='unresolved'&&evidence.length===0} value={evidenceExplanation} onChange={e=>setEvidenceExplanation(e.target.value)} rows={3} placeholder="指出可核查的具体错误、方法障碍或反例；非“暂未解决”需要证据引用或说明。"/></label><label className="field-label">值得重试的条件（每行一项）<textarea value={retryConditions} onChange={e=>setRetryConditions(e.target.value)} rows={3} placeholder="例如：增加谱隙假设后重新检查。"/></label></>}
    {action==='proof'&&<><fieldset className="choice-list"><legend>共同前提（本方案同时依赖）</legend>{list.filter(o=>o.kind==='claim'&&o.id!==selected?.id).map(o=><label key={o.id}><input type="checkbox" checked={premises.includes(o.revision.id)} onChange={()=>toggle(premises,o.revision.id,setPremises)}/><MathPreview body={o.revision.body}/></label>)}{!list.some(o=>o.kind==='claim'&&o.id!==selected?.id)&&<p>没有其他命题，可先写不引用前提的完整论证。</p>}</fieldset><fieldset className="choice-list"><legend>上下文</legend>{list.filter(o=>o.kind==='context').map(o=><label key={o.id}><input type="checkbox" checked={contexts.includes(o.revision.id)} onChange={()=>toggle(contexts,o.revision.id,setContexts)}/><MathPreview body={o.revision.body}/></label>)}</fieldset><fieldset className="choice-list"><legend>暂时假设成立的命题（保持条件性）</legend>{list.filter(o=>o.kind==='claim'&&o.id!==selected?.id).map(o=><label key={o.id}><input type="checkbox" checked={assumptions.includes(o.revision.id)} onChange={()=>toggle(assumptions,o.revision.id,setAssumptions)}/><MathPreview body={o.revision.body}/></label>)}</fieldset><label className="field-label">尚未补全的步骤（每行一项）<textarea value={gaps} onChange={e=>setGaps(e.target.value)} rows={3}/></label></>}
    <MathInputHint/><div className="modal-actions"><button type="button" onClick={onClose}>取消</button><button className="primary" disabled={busy}>{busy?'正在保存…':action==='project'?'创建研究':action==='run'||action==='review-run'?'开始执行':'保存'}</button></div>
  </form></Modal>
}




