import { useEffect, useState } from 'react'
import { post, request } from './api'
import { Badge, Modal, shortId } from './ui'
import type { ProviderStatus } from './ActionDialog'
import { AgentPolicyPanel } from './AgentPolicyPanel'

export interface RuntimeSettings {project_id:string;request_budget:number;allow_real_api:boolean;allowed_providers:string[]}
interface RequestRecord {request_id:string;run_id:string;provider:string;state:string;reason:string;usage:Record<string,number>;simulated:boolean}
export interface Budget {request_budget:number;reserved:number;dispatched:number;spent:number;unknown:number;released:number;remaining:number;requests:RequestRecord[]}
interface CodeSandbox {enabled:boolean;ready:boolean;reason:string;image_id:string}
export function BudgetPanel({projectId,budget,providers,onRefresh}:{projectId:string;budget:Budget|null;providers:ProviderStatus[];onRefresh:()=>Promise<void>}){
  const [settings,setSettings]=useState<RuntimeSettings|null>(null),[sandbox,setSandbox]=useState<CodeSandbox|null>(null),[editing,setEditing]=useState(false),[reconcile,setReconcile]=useState<RequestRecord|null>(null),[outcome,setOutcome]=useState('spent'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[sandboxBusy,setSandboxBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{request<RuntimeSettings>(`/projects/${projectId}/runtime-settings`).then(setSettings).catch(e=>setError(e.message));request<CodeSandbox>(`/projects/${projectId}/code-sandbox`).then(setSandbox).catch(e=>setError(e.message))},[projectId,editing])
  async function save(){if(!settings)return;setBusy(true);setError('');try{await request(`/projects/${projectId}/runtime-settings`,{method:'PUT',body:JSON.stringify({request_budget:settings.request_budget,allow_real_api:settings.allow_real_api,allowed_providers:settings.allowed_providers})});setEditing(false);await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function settle(){if(!reconcile)return;setBusy(true);setError('');try{await post(`/requests/${reconcile.request_id}/reconcile`,{outcome,reason});setReconcile(null);await onRefresh()}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function setSandboxEnabled(enabled:boolean){if(!sandbox)return;setSandboxBusy(true);setError('');try{const next=await request<CodeSandbox>(`/projects/${projectId}/code-sandbox`,{method:'PUT',body:JSON.stringify({enabled})});setSandbox(next);await onRefresh()}catch(e){setError((e as Error).message);const current=await request<CodeSandbox>(`/projects/${projectId}/code-sandbox`).catch(()=>null);if(current)setSandbox(current)}finally{setSandboxBusy(false)}}
  return <section className="budget-panel" aria-label="请求额度与调用账本"><div className="budget-strip"><strong>项目请求额度</strong><span>{budget?`剩余 ${budget.remaining} / ${budget.request_budget}`:'正在读取…'}</span><button onClick={()=>{setError('');setEditing(true)}}>运行设置</button><AgentPolicyPanel projectId={projectId} onRefresh={onRefresh}/></div>{sandbox&&<div className="detail-note" aria-label="离线代码沙箱设置"><div className="section-actions"><strong>离线代码沙箱</strong><button type="button" onClick={()=>{request<CodeSandbox>(`/projects/${projectId}/code-sandbox`).then(setSandbox).catch(e=>setError(e.message))}} disabled={sandboxBusy}>刷新状态</button></div><p>{sandbox.enabled?'已启用':'未启用'} · {sandbox.ready?'引擎就绪':'环境不可用'}{sandbox.image_id&&` · ${sandbox.image_id}`}</p>{sandbox.reason&&<p className="subtle">{sandbox.reason}</p>}<button type="button" onClick={()=>setSandboxEnabled(!sandbox.enabled)} disabled={sandboxBusy||(!sandbox.enabled&&!sandbox.ready)}>{sandbox.enabled?'关闭沙箱':'启用沙箱'}</button><p className="subtle">隔离环境提供 Python 与 SymPy，禁止联网；计算结果不等于完整证明。</p></div>}{budget&&<><div className="budget-counts"><span>预留 {budget.reserved}</span><span>已发出 {budget.dispatched}</span><span>已使用 {budget.spent}</span><span className={budget.unknown?'attention':''}>待对账 {budget.unknown}</span><span>已释放 {budget.released}</span><small>单位为请求次数；费用以提供方账单为准。模拟请求单独标识。</small></div>{budget.requests.length>0&&<details className="ledger"><summary>查看请求记录{budget.unknown?` · ${budget.unknown} 项需要对账`:''}</summary>{budget.requests.slice().reverse().map(r=><div className="ledger-row" key={r.request_id}><div><span>{r.simulated?'模拟执行':r.provider}</span><Badge state={r.state}/><code>{shortId(r.request_id)}</code></div><small>任务 {shortId(r.run_id)}{r.reason?` · ${r.reason}`:''}</small>{Object.keys(r.usage).length>0&&<small>{Object.entries(r.usage).map(([k,v])=>`${k}: ${v}`).join(' · ')}</small>}{r.state==='unknown'&&<button onClick={()=>{setReconcile(r);setReason('');setOutcome('spent');setError('')}}>记录人工对账结果</button>}</div>)}</details>}</>}
    {editing&&<Modal title="项目运行设置" onClose={()=>setEditing(false)}><form onSubmit={e=>{e.preventDefault();save()}}>{error&&<p role="alert" className="inline-error">{error}</p>}{settings&&<><label className="field-label">项目累计请求上限<input type="number" min={0} max={1000000} required value={settings.request_budget} onChange={e=>setSettings({...settings,request_budget:Number(e.target.value)})}/></label><p className="subtle">已使用、已发出、预留和结果不明的请求都占用额度。单个任务还受各自请求上限约束。</p><label className="checkbox-label"><input type="checkbox" checked={settings.allow_real_api} onChange={e=>setSettings({...settings,allow_real_api:e.target.checked})}/>允许本项目调用已配置的真实模型</label><fieldset className="choice-list"><legend>允许使用的执行后端</legend>{['fake','deepseek','glm'].map(name=>{const p=providers.find(p=>p.provider===name);return <label key={name}><input type="checkbox" checked={settings.allowed_providers.includes(name)} onChange={e=>setSettings({...settings,allowed_providers:e.target.checked?[...settings.allowed_providers,name]:settings.allowed_providers.filter(v=>v!==name)})}/><span>{name==='fake'?'模拟执行':name}{name!=='fake'&&<small> · {p?.enabled?'本机已配置':'需在本机配置并启用 API'}</small>}</span></label>})}</fieldset><p className="subtle">此处不接收密钥。密钥、模型名称与总开关由本机启动环境提供。</p></>}<div className="modal-actions"><button type="button" onClick={()=>setEditing(false)}>取消</button><button className="primary" disabled={busy||!settings?.allowed_providers.length}>保存设置</button></div></form></Modal>}
    {reconcile&&<Modal title="记录调用对账结果" onClose={()=>setReconcile(null)}><form onSubmit={e=>{e.preventDefault();settle()}}><p className="subtle">核对提供方的调用记录后登记结论。对账不会生成研究产物；之后可手动恢复任务。</p>{error&&<p className="inline-error" role="alert">{error}</p>}<label className="field-label">确认结果<select value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="spent">请求已被接受，保留已用额度</option><option value="unaccepted">确认请求未被接受，释放额度</option></select></label><label className="field-label">核对依据<textarea required rows={4} value={reason} onChange={e=>setReason(e.target.value)} placeholder="记录调用编号、核对时间及依据"/></label><div className="modal-actions"><button type="button" onClick={()=>setReconcile(null)}>取消</button><button className="primary" disabled={busy||!reason.trim()}>保存对账记录</button></div></form></Modal>}
  </section>
}
