import { useEffect, useState } from 'react'
import type { ResearchObject, Revision, Snapshot } from './api'
import { ApiError, post, request } from './api'
import { Badge, evidenceLabels, kindLabels, MathInputHint, MathPreview, MathText, shortId } from './ui'
import { draftKey, getDraft, saveDraft } from './drafts'

export function Inspector({object,snapshot,onRefresh,onSelect,onAction,onNotice,onClose,historicalId}:{object:ResearchObject;snapshot:Snapshot;onRefresh:()=>Promise<void>;onSelect:(id:string)=>void;onAction:(type:string)=>void;onNotice:(message:string)=>void;onClose:()=>void;historicalId?:string|null}){
  const key=draftKey(snapshot.branch.id,object.id)
  const [draft]=useState(()=>getDraft(key))
  const [tab,setTab]=useState('statement'),[editing,setEditing]=useState(Boolean(draft)),[base,setBase]=useState(draft?.base||object.revision),[body,setBody]=useState(draft?.body??object.revision.body),[role,setRole]=useState(draft?.role||String(object.revision.payload.role||'assumption')),[busy,setBusy]=useState(false),[revisions,setRevisions]=useState<Revision[]>([]),[compare,setCompare]=useState<string|null>(null)
  const [localError,setLocalError]=useState('')
  useEffect(()=>saveDraft(key,editing?{base,body,role}:null),[key,editing,base,body,role])
  useEffect(()=>{if(!editing){setBase(object.revision);setBody(object.revision.body);setRole(String(object.revision.payload.role||'assumption'))}},[object.revision.id,editing])
  useEffect(()=>{if(tab==='history'||historicalId)request<{revisions:Revision[]}>(`/objects/${object.id}/revisions`).then(r=>setRevisions(r.revisions)).catch(e=>setLocalError(e.message));if(historicalId){setTab('history');setCompare(historicalId)}},[tab,object.id,object.revision.id,historicalId])
  const support=snapshot.support.claims[object.revision.id]||snapshot.support.plans[object.revision.id]
  const proofs=snapshot.proof_plans.filter(p=>p.conclusion_revision_id===object.revision.id||p.revision_id===object.revision.id)
  const evidence=snapshot.reviews.filter(r=>r.target_revision_id===object.revision.id)
  const comments=snapshot.annotations?.filter(a=>a.revision_id===object.revision.id)||[]
  const describe=(rid:string)=>snapshot.objects.find(o=>o.revision.id===rid)?.revision.body||`历史版本 ${shortId(rid)}`
  async function save(){setBusy(true);setLocalError('');try{const payload=object.kind==='context'?{...base.payload,role}:base.payload;const result=await post<{affected_plan_revision_ids:string[];stale_run_ids:string[]}>(`/objects/${object.id}/revisions`,{branch_id:snapshot.branch.id,expected_revision_id:base.id,body,payload});setEditing(false);await onRefresh();onNotice(`新版本已保存；${result.affected_plan_revision_ids.length} 项论证需要重查，${result.stale_run_ids.length} 个运行仍读取旧版。`)}catch(error){if(error instanceof ApiError&&error.status===409){setEditing(false);await onRefresh();onNotice('其他修改先一步保存。你的内容已保留为冲突候选，可在下方比较处理。')}else setLocalError((error as Error).message)}finally{setBusy(false)}}
  async function adopt(state:string){setBusy(true);try{await post('/adoptions',{branch_id:snapshot.branch.id,revision_id:object.revision.id,state,reason:state==='adopted'?'用户在工作台暂时采用；证据状态单独保留。':'用户在工作台撤回当前采用。'});await onRefresh();onNotice(state==='adopted'?'已记录人工采用，证据状态保持独立。':'已撤回采用；原版本和证据仍然保留。')}catch(e){setLocalError((e as Error).message)}finally{setBusy(false)}}
  const conflicts=snapshot.conflicts.filter(c=>c.object_id===object.id&&!c.resolution)
  return <aside className="inspector" aria-label="对象详情"><div className="inspector-top"><span>{kindLabels[object.kind]}详情</span><button className="icon-button" onClick={onClose} aria-label="关闭对象详情">×</button></div><div className="inspector-state"><Badge state={object.adoption_state}/>{support&&<Badge state={support.status}/>}<code>{shortId(object.revision.id)}</code></div>
    <div className="inspector-tabs" role="tablist" aria-label="详情内容">{[['statement','正文'],['proof','论证'],['evidence','证据'],['history','版本'],['notes','批注']].map(([value,label])=><button key={value} role="tab" aria-selected={tab===value} className={tab===value?'active':''} onClick={()=>setTab(value)}>{label}</button>)}</div>
    <div className="inspector-content">{localError&&<p role="alert" className="inline-error">{localError}</p>}
    {tab==='statement'&&<>{editing?<><label className="field-label">正文<textarea aria-label="编辑对象正文" value={body} onChange={e=>setBody(e.target.value)} rows={12}/></label>{object.kind==='context'&&<label className="field-label">上下文类型<select value={role} onChange={e=>setRole(e.target.value)}><option value="assumption">假设（作为条件保留）</option><option value="definition">定义</option><option value="convention">符号约定</option></select></label>}{base.id!==object.revision.id&&<p className="inline-warning">后台已产生新版本。你的草稿不会被覆盖，保存时会进行冲突检查。</p>}<div className="button-row"><button className="primary" disabled={busy||!body.trim()} onClick={save}>保存新版本</button><button onClick={()=>setEditing(false)}>取消编辑</button></div><MathInputHint/><details className="preview-details"><summary>公式预览</summary><MathText body={body}/></details></>:<><div className="math-body"><MathText body={object.revision.body}/></div><div className="button-row"><button className="primary" onClick={()=>setEditing(true)}>编辑正文</button><button onClick={()=>onAction('run')}>从此处研究</button></div></>}
      {object.kind==='context'&&<div className="detail-note">上下文：{({assumption:'尚未解除的假设',definition:'定义',convention:'符号约定'} as Record<string,string>)[String(object.revision.payload.role||'assumption')]}</div>}
      {Boolean(object.revision.payload.simulated)&&<p className="detail-note">模拟执行产物，用于验证工作流。</p>}
      {Boolean(object.revision.payload.outcome)&&<div className="detail-note">研究结果：<Badge state={String(object.revision.payload.outcome)}/></div>}
      {object.revision.payload.artifact_type==='failure'&&<FailureDetails payload={object.revision.payload} describe={describe}/>}
      {object.revision.payload.artifact_type==='source'&&<SourceDetails payload={object.revision.payload}/>}
      {support?.conditions?.length>0&&<section className="detail-section"><h3>尚未解除的条件</h3>{support.conditions.map(rid=><div key={rid}><MathText body={describe(rid)}/></div>)}</section>}
      <section className="detail-section"><h3>项目采用</h3><p className="subtle">采用记录与论证证据分别保存。</p><div className="button-row"><button disabled={busy||object.adoption_state==='adopted'} onClick={()=>adopt('adopted')}>暂时采用</button><button disabled={busy||object.adoption_state==='withdrawn'} onClick={()=>adopt('withdrawn')}>撤回采用</button><button onClick={()=>onAction('branch')}>从此处分支</button></div></section>
    </>}
    {tab==='proof'&&<><div className="section-actions"><h3>{object.kind==='argument'?'本方案的前提':'替代证明方案'}</h3>{object.kind==='claim'&&<button onClick={()=>onAction('proof')}>＋ 添加方案</button>}</div>{proofs.length?proofs.map((p,i)=><section className="proof-card" key={p.revision_id}><div className="proof-title"><strong>方案 {i+1}</strong><Badge state={snapshot.support.plans[p.revision_id]?.status||'draft'}/></div><MathText body={p.body}/>{(['premise','context','assumption'] as const).map(key=>{const ids=p[`${key}_revision_ids`];return ids.length>0&&<div key={key} className="dependency-list"><h4>{({premise:'共同前提（全部需要）',context:'上下文',assumption:'未解除假设'})[key]}</h4>{ids.map(rid=><button key={rid} onClick={()=>{const o=snapshot.objects.find(o=>o.revision.id===rid);if(o)onSelect(o.id)}}><MathPreview body={describe(rid)}/></button>)}</div>})}{p.gaps.length>0&&<div className="inline-warning">缺口：{p.gaps.map((gap,index)=><MathText key={index} body={gap}/>)}</div>}{object.kind!=='argument'&&<button onClick={()=>{const o=snapshot.objects.find(o=>o.revision.id===p.revision_id);if(o)onSelect(o.id)}}>打开论证详情</button>}</section>):<p className="subtle">还没有记录证明方案。可以先写草稿，再补充前提与依据。</p>}<p className="support-footnote">支持状态根据明确记录的依赖和证据计算，不代表自动判定数学真伪。</p></>}
    {tab==='evidence'&&<><div className="section-actions"><h3>当前版本的证据</h3><button onClick={()=>onAction('review')}>记录审查</button></div>{evidence.length?evidence.map(r=><section key={r.id} className="evidence-card"><strong>{evidenceLabels[r.kind]||r.kind}</strong><span className="evidence-verdict">{({passed:'未发现问题',issues:'发现问题',inconclusive:'仍未确定'} as Record<string,string>)[r.verdict]}</span><MathText body={r.scope}/><ul>{r.findings.map((finding,i)=><li key={i}><MathText body={finding}/></li>)}</ul><small>{r.coverage==='whole_plan'?'覆盖整份论证':'局部范围'} · {r.author}</small></section>):<p className="subtle">当前版本还没有证据记录。旧版审查可以在版本历史中查阅。</p>}<button onClick={()=>onAction('review-run')}>请求独立模型审查</button></>}
    {tab==='history'&&<><h3>版本历史</h3><div className="version-list">{revisions.map((r,i)=><button key={r.id} className={compare===r.id?'active':''} onClick={()=>setCompare(r.id)}><span>v{i+1} {r.id===object.revision.id?'· 当前':''}</span><code>{shortId(r.id)}</code></button>)}</div>{compare&&revisions.find(r=>r.id===compare)&&<section className="version-compare"><h4>选定版本</h4><MathText body={revisions.find(r=>r.id===compare)!.body}/><h4>当前版本</h4><MathText body={object.revision.body}/>{snapshot.reviews.filter(r=>r.target_revision_id===compare).map(r=><div className="detail-note" key={r.id}>{evidenceLabels[r.kind]}：<MathText body={r.scope}/><ul>{r.findings.map((f,i)=><li key={i}><MathText body={f}/></li>)}</ul></div>)}{snapshot.annotations?.filter(a=>a.revision_id===compare).map(a=><section className="annotation" key={a.id}><strong>此版本的批注</strong>{a.anchor_quote&&<blockquote><MathText body={a.anchor_quote}/></blockquote>}<MathText body={a.body}/><small>{a.author} · {new Date(a.created_at).toLocaleString('zh-CN')}</small></section>)}</section>}</>}
    {tab==='notes'&&<><div className="section-actions"><h3>版本批注</h3><button onClick={()=>onAction('annotation')}>＋ 添加批注</button></div>{comments.length?comments.map(a=><section className="annotation" key={a.id}>{a.anchor_quote&&<blockquote><MathText body={a.anchor_quote}/></blockquote>}<MathText body={a.body}/><small>{a.author} · {new Date(a.created_at).toLocaleString('zh-CN')}</small></section>):<p className="subtle">可以针对整份正文或具体句子提出疑问。</p>}</>}
    {conflicts.length>0&&<section className="conflict-box"><h3>有待处理的修改冲突</h3>{conflicts.map(c=><ConflictChoice key={c.id} conflict={c} object={object} branchId={snapshot.branch.id} onRefresh={onRefresh} onNotice={onNotice}/>)}</section>}
    </div>
  </aside>
}

function FailureDetails({payload,describe}:{payload:Record<string,unknown>;describe:(revisionId:string)=>string}){
  const ids=(key:string)=>Array.isArray(payload[key])?(payload[key] as unknown[]).filter((value):value is string=>typeof value==='string'):[]
  return <section className="detail-section"><h3>尝试范围与重试条件</h3><p><strong>目标版本：</strong>{String(payload.target_revision_id||'未记录')}</p>{Boolean(payload.target_revision_id)&&<MathText body={describe(String(payload.target_revision_id))}/>}<strong>适用范围：</strong><MathText body={String(payload.scope||payload.evidence_scope||'未记录')}/>{ids('assumption_revision_ids').length>0&&<><h4>前提版本</h4><ul>{ids('assumption_revision_ids').map(id=><li key={id}><MathText body={describe(id)}/> <code>{shortId(id)}</code></li>)}</ul></>}{ids('evidence_revision_ids').length>0&&<><h4>证据版本</h4><ul>{ids('evidence_revision_ids').map(id=><li key={id}><MathText body={describe(id)}/> <code>{shortId(id)}</code></li>)}</ul></>}{Boolean(payload.evidence_explanation)&&<MathText body={String(payload.evidence_explanation)}/>}<h4>何时值得重试</h4>{ids('retry_conditions').length?<ul>{ids('retry_conditions').map((item,index)=><li key={index}><MathText body={item}/></li>)}</ul>:<p className="subtle">尚未记录具体重试条件。</p>}</section>
}

function SourceDetails({payload}:{payload:Record<string,unknown>}){
  const identifier=String(payload.url_or_identifier||'')
  const safeLink=/^https?:\/\//i.test(identifier)?identifier:null
  return <section className="detail-section"><h3>来源信息</h3><dl className="source-details"><dt>题名</dt><dd><MathText body={String(payload.title||'未记录')}/></dd><dt>作者</dt><dd>{Array.isArray(payload.authors)&&payload.authors.length?payload.authors.join('、'):'未知'}</dd><dt>链接或标识</dt><dd>{safeLink?<a href={safeLink} target="_blank" rel="noreferrer noopener">{identifier}</a>:identifier||'未记录'}</dd><dt>定位</dt><dd><MathText body={String(payload.locator||'未记录')}/></dd><dt>访问日期</dt><dd>{String(payload.accessed_on||'未记录')}</dd><dt>核对状态</dt><dd>{payload.verification==='provided'?'已提供来源材料':'来源待核对'}</dd></dl></section>
}

function ConflictChoice({conflict,object,branchId,onRefresh,onNotice}:{conflict:Snapshot['conflicts'][number];object:ResearchObject;branchId:string;onRefresh:()=>Promise<void>;onNotice:(message:string)=>void}){
  const [candidate,setCandidate]=useState<Revision|null>(null),[busy,setBusy]=useState(false)
  useEffect(()=>{request<{revisions:Revision[]}>(`/objects/${object.id}/revisions`).then(r=>setCandidate(r.revisions.find(v=>v.id===conflict.candidate_revision_id)||null))},[object.id,conflict.candidate_revision_id])
  async function resolve(rid:string){setBusy(true);try{await post(`/conflicts/${conflict.id}/resolve`,{branch_id:branchId,expected_current_revision_id:object.revision.id,selected_revision_id:rid});await onRefresh();onNotice('冲突已处理，两个修改版本都保留在历史中。')}catch(e){onNotice((e as Error).message)}finally{setBusy(false)}}
  return <div><p>你的候选版本</p>{candidate&&<MathText body={candidate.body}/>}<details><summary>比较当前版本</summary><MathText body={object.revision.body}/></details><div className="button-row"><button disabled={busy} onClick={()=>resolve(conflict.candidate_revision_id)}>采用候选内容</button><button disabled={busy} onClick={()=>resolve(object.revision.id)}>保留当前内容</button></div></div>
}

