import { useEffect, useState } from 'react'
import { post, request } from './api'
import { defaultRunOptions, RunOptionsFields } from './RunOptions'
import type { RunOptions } from './RunOptions'
import { Badge, MathText, Modal, shortId, dialogueReasonLabels } from './ui'

export function RunSettings({runId,state,onRefresh,onNotice}:{runId:string;state:string;onRefresh:()=>Promise<void>;onNotice:(message:string)=>void}){
  const [open,setOpen]=useState(false),[value,setValue]=useState<RunOptions|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('')
  async function load(){setOpen(true);setValue(null);setError('');try{const loaded=await request<RunOptions>(`/runs/${runId}/options`);setValue(Object.fromEntries(Object.keys(defaultRunOptions).map(key=>[key,loaded[key as keyof RunOptions]??defaultRunOptions[key as keyof RunOptions]])) as unknown as RunOptions)}catch(e){setError((e as Error).message)}}
  async function save(resume:boolean){if(!value)return;setBusy(true);setError('');try{await request(`/runs/${runId}/options`,{method:'PUT',body:JSON.stringify(value)});if(resume)await post(`/runs/${runId}/resume`);await onRefresh();setOpen(false);onNotice(resume?'任务设置已保存，并从当前有效进度恢复。':'任务设置已保存；仍受项目与分支总额度限制。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <><button onClick={load}>{['budget_exhausted','step_limit'].includes(state)?'调整额度并恢复':'任务额度与研究设置'}</button>{open&&<Modal title="任务额度与研究设置" onClose={()=>setOpen(false)}>{error&&<p className="inline-error" role="alert">{error}</p>}{value&&value.solver_controller!=='continuous_research'?<><p>这是历史求解流程，仅保留记录。需要继续研究时，请从原题新建连续研究任务。</p><dl className="source-details"><dt>请求上限</dt><dd>{value.request_budget}</dd><dt>累计输出上限</dt><dd>{value.cumulative_output_token_budget??'未限制'}</dd></dl><div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>关闭</button></div></>:<form onSubmit={event=>{event.preventDefault();save(false)}}>{value?<RunOptionsFields value={value} onChange={setValue} allowAutonomyChange={false}/>:!error&&<p>正在读取任务设置…</p>}<p className="subtle">额度指累计上限。恢复前还需项目与分支均有剩余额度；已发出的请求继续按原设置结算。</p><div className="modal-actions"><button type="button" onClick={()=>setOpen(false)}>取消</button><button className="primary" disabled={busy||!value}>保存设置</button>{['budget_exhausted','step_limit','paused','failed','interrupted'].includes(state)&&<button type="button" disabled={busy||!value} onClick={()=>save(true)}>保存并恢复任务</button>}</div></form>}</Modal>}</>
}

export function BranchRuntimeControls({branchId,archived,eventSeq,onRefresh,onNotice}:{branchId:string;archived:boolean;eventSeq:number;onRefresh:()=>Promise<void>;onNotice:(message:string)=>void}){
  const [settings,setSettings]=useState<{request_budget:number;state:string}|null>(null),[editing,setEditing]=useState(false),[limit,setLimit]=useState(100),[steering,setSteering]=useState(false),[instruction,setInstruction]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('')
  useEffect(()=>{let cancelled=false;request<{request_budget:number;state:string}>(`/branches/${branchId}/runtime-settings`).then(value=>{if(!cancelled)setSettings(value)}).catch(e=>{if(!cancelled)setError(e.message)});return()=>{cancelled=true}},[branchId,eventSeq])
  async function action(action:string){setBusy(true);setError('');try{await post(`/branches/${branchId}/interventions`,{action,instruction:action==='steer'?instruction:''});await onRefresh();setSteering(false);onNotice('分支指令已记录；在途请求将在可控边界响应。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  async function save(){setBusy(true);setError('');try{await request(`/branches/${branchId}/runtime-settings`,{method:'PUT',body:JSON.stringify({request_budget:limit})});setEditing(false);await onRefresh();onNotice('分支累计请求上限已保存。')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
  return <section className="branch-runtime" aria-label="分支运行控制"><div className="section-actions"><div><strong>当前分支</strong> {settings&&<span>累计请求上限 {settings.request_budget} · {archived?'已归档':settings.state==='paused'?'已暂停':settings.state==='cancelled'?'已停止':'允许派工'}</span>}</div><button disabled={!settings} onClick={()=>{setLimit(settings!.request_budget);setError('');setEditing(true)}}>分支额度</button></div>{error&&<p className="inline-error" role="alert">{error}</p>}<div className="button-row"><button disabled={busy} onClick={()=>action('pause')}>暂停整个分支</button><button disabled={busy} onClick={()=>action('cancel')}>停止整个分支</button><button disabled={busy} onClick={()=>{setInstruction('');setError('');setSteering(true)}}>向分支任务插话</button><button disabled={busy||archived} onClick={()=>action('resume')}>恢复分支任务</button></div>{archived&&<p className="subtle">先在地图显示设置中取消分支归档，再恢复任务。</p>}
    {editing&&<Modal title="分支请求额度" onClose={()=>setEditing(false)}><form onSubmit={event=>{event.preventDefault();save()}}>{error&&<p className="inline-error" role="alert">{error}</p>}<label className="field-label">分支累计请求上限<input required type="number" min={0} max={1000000} value={limit} onChange={event=>setLimit(Number(event.target.value))}/></label><p className="subtle">分支任务共用此额度，同时受项目总额度限制。修改额度不会自动恢复已暂停任务。</p><div className="modal-actions"><button type="button" onClick={()=>setEditing(false)}>取消</button><button className="primary" disabled={busy}>保存分支额度</button></div></form></Modal>}
    {steering&&<Modal title="对整个分支插话" onClose={()=>setSteering(false)}><form onSubmit={event=>{event.preventDefault();action('steer')}}>{error&&<p className="inline-error" role="alert">{error}</p>}<label className="field-label">新的分支指令<textarea rows={5} required value={instruction} onChange={event=>setInstruction(event.target.value)}/></label><p className="subtle">作用于此分支符合条件的任务；后续步骤读取新指令，旧结果保留版本隔离。</p><div className="modal-actions"><button type="button" onClick={()=>setSteering(false)}>取消</button><button className="primary" disabled={busy}>发送分支指令</button></div></form></Modal>}
  </section>
}

interface Step {id:string;number:number;state:string;body:string;actions:{type:string;status:string;result?:unknown;error?:unknown}[];created_at:string;output_revision_id?:string}
interface Call {request_id:string;attempt_id:string;call_config:{provider:string;model:string;parameters:Record<string,unknown>;prompt_template_version:string;prompt_sha256:string;research_context?:{dialogue_id:string;member:string;previous_input_preserved:boolean|null;reset_reason:string|null;capacity:number|null;input_estimate:number|null}};raw_text:string;raw_sha256:string;raw_text_truncated?:boolean;finish_reason:string|null;complete:boolean;usage:Record<string,unknown>;provider_request_id:string|null;created_at:string}
function CallUsage({call}:{call:Call}){
  const number=(key:string)=>typeof call.usage?.[key]==='number'?(call.usage[key] as number).toLocaleString():'未提供'
  const context=call.call_config?.research_context
  return <div className="call-usage"><p>已报告输入 {number('prompt_tokens')} · 已报告输出 {number('completion_tokens')} · 缓存命中 {number('prompt_cache_hit_tokens')} · 未命中 {number('prompt_cache_miss_tokens')}</p>{context&&<p className="subtle">当前对话 {shortId(context.dialogue_id)}{context.reset_reason?` · ${dialogueReasonLabels[context.reset_reason]||context.reset_reason}`:context.previous_input_preserved===true?' · 旧输入原样保留（本地接续记录，不代表服务端命中）':context.previous_input_preserved===false?' · 旧输入或模型配置发生变化':' · 尚无接续比较'}{typeof context.capacity==='number'&&<> · 对话容量 {context.capacity.toLocaleString()}</>}{context.input_estimate!==null&&context.input_estimate!==undefined&&<> · 输入粗估 {context.input_estimate.toLocaleString()}（不是精确计数）</>}</p>}</div>
}
export function RunTrace({runId,eventSeq}:{runId:string;eventSeq:number}){
  const [open,setOpen]=useState(false),[steps,setSteps]=useState<Step[]>([]),[calls,setCalls]=useState<Call[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(false)
  useEffect(()=>{if(!open)return;let cancelled=false;setLoading(true);Promise.all([request<{steps:Step[]}>(`/runs/${runId}/steps`),request<{calls:Call[]}>(`/runs/${runId}/calls`)]).then(([s,c])=>{if(!cancelled){setSteps(s.steps);setCalls(c.calls);setError('')}}).catch(e=>{if(!cancelled)setError(e.message)}).finally(()=>{if(!cancelled)setLoading(false)});return()=>{cancelled=true}},[runId,eventSeq,open])
  return <details className="run-trace" onToggle={event=>setOpen(event.currentTarget.open)}><summary>研究步骤、调用配置与可见原输出</summary>{error&&<p className="inline-error" role="alert">{error}</p>}{loading&&<p className="subtle">正在读取执行记录…</p>}{!loading&&!error&&steps.length===0&&calls.length===0&&<p className="subtle">尚无已记录的研究步骤或模型调用。</p>}{steps.map(step=><section className="trace-step" key={step.id}><div><strong>步骤 {step.number}</strong> <Badge state={step.state}/></div><MathText body={step.body||'本步骤没有正文输出。'}/>{step.actions?.length>0&&<ul>{step.actions.map((action,index)=><li key={index}><strong>{actionLabels[action.type]||action.type}</strong> · {action.status}{Boolean(action.error)&&<p className="inline-warning">{typeof action.error==='string'?action.error:JSON.stringify(action.error)}</p>}{action.result!==undefined&&<details><summary>操作回执</summary><pre>{JSON.stringify(action.result,null,2)}</pre></details>}</li>)}</ul>}</section>)}{calls.map(call=><section className="trace-call" key={call.request_id}><div><strong>{call.call_config?.provider||'模型调用'} · {call.call_config?.model||'未记录模型名称'}</strong><span>{call.complete?'完整响应':'不完整响应'}{call.finish_reason?` · ${call.finish_reason}`:''}</span></div><small>调用 {shortId(call.request_id)} · {call.created_at?new Date(call.created_at).toLocaleString('zh-CN'):''}</small><CallUsage call={call}/><details><summary>本次参数、用量与提示版本</summary><dl className="source-details"><dt>提示模板</dt><dd>{call.call_config?.prompt_template_version||'未记录'}</dd><dt>提示指纹</dt><dd><code>{call.call_config?.prompt_sha256||'未记录'}</code></dd><dt>提供方请求号</dt><dd>{call.provider_request_id||'未返回'}</dd></dl><pre>{JSON.stringify({parameters:call.call_config?.parameters||{},usage:call.usage||{}},null,2)}</pre></details><details><summary>查看可见原输出{!call.complete?'（可能中断）':''}</summary><p className="subtle">这是提供方实际返回的可见文本。内容仅作研究记录，不等于数学结论已成立。</p>{call.raw_text_truncated&&<p className="inline-warning">本记录仅保留原输出前段。</p>}<pre className="raw-output">{call.raw_text||'本次未收到可见文本。'}</pre><small>输出指纹 {call.raw_sha256||'未记录'}</small></details></section>)}</details>
}
const actionLabels:Record<string,string>={read_material:'读取研究材料',save_note:'保存工作稿或推导',compute:'离线计算',assign_work:'调整局部任务',send_message:'发送话题消息',finish_work:'结束局部任务',submit_solution:'提交解答',read_object:'读取对象',search_project:'检索项目',write_draft:'保存草稿',propose_proof:'提出证明方案',record_failure:'记录失败',request_review:'请求审查',spawn_task:'提出子任务',discuss:'项目讨论',finish:'结束研究',revise_object:'修订对象'}
