"""Initial immutable foundation schema."""

import sqlalchemy as sa
from alembic import op

revision = "0001_foundation"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_receipts",
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("operation", sa.String(), nullable=False),
        sa.Column("digest", sa.String(), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=False),
        sa.Column("response", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "projects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("original_goal_id", sa.String(), nullable=True),
        sa.Column("policies", sa.JSON(), nullable=False),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "branches",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=True),
        sa.Column("control_epoch", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("project_id", "name"),
    )
    op.create_index(op.f("ix_branches_project_id"), "branches", ["project_id"], unique=False)
    op.create_table(
        "objects",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_objects_project_id"), "objects", ["project_id"], unique=False)
    op.create_table(
        "events",
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("seq", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.PrimaryKeyConstraint("project_id", "seq"),
        sa.UniqueConstraint("id"),
    )
    op.create_table(
        "relations",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("source_id", sa.String(), nullable=False),
        sa.Column("target_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["source_id"],
            ["objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_relations_branch_id"), "relations", ["branch_id"], unique=False)
    op.create_table(
        "revisions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_revisions_object_id"), "revisions", ["object_id"], unique=False)
    op.create_table(
        "runs",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("goal_object_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("control_epoch", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("instruction", sa.Text(), nullable=False),
        sa.Column("current_attempt_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["goal_object_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_runs_branch_id"), "runs", ["branch_id"], unique=False)
    op.create_table(
        "adoptions",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("event_seq", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_adoptions_branch_id"), "adoptions", ["branch_id"], unique=False)
    op.create_index(op.f("ix_adoptions_revision_id"), "adoptions", ["revision_id"], unique=False)
    op.create_table(
        "attempts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("run_id", sa.String(), nullable=False),
        sa.Column("number", sa.Integer(), nullable=False),
        sa.Column("state", sa.String(), nullable=False),
        sa.Column("read_set", sa.JSON(), nullable=False),
        sa.Column("control_epoch", sa.Integer(), nullable=False),
        sa.Column("token", sa.String(), nullable=False),
        sa.Column("lease_until", sa.String(), nullable=False),
        sa.Column("checkpoint", sa.JSON(), nullable=False),
        sa.Column("output_revision_id", sa.String(), nullable=True),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["output_revision_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("run_id", "number"),
    )
    op.create_index(op.f("ix_attempts_run_id"), "attempts", ["run_id"], unique=False)
    op.create_table(
        "branch_heads",
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("branch_id", "object_id"),
    )
    op.create_index(
        op.f("ix_branch_heads_revision_id"), "branch_heads", ["revision_id"], unique=False
    )
    op.create_table(
        "conflicts",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("object_id", sa.String(), nullable=False),
        sa.Column("expected_revision_id", sa.String(), nullable=False),
        sa.Column("current_revision_id", sa.String(), nullable=False),
        sa.Column("candidate_revision_id", sa.String(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["candidate_revision_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["current_revision_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["expected_revision_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["object_id"],
            ["objects.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_conflicts_branch_id"), "conflicts", ["branch_id"], unique=False)
    op.create_table(
        "manuscript_blocks",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("branch_id", sa.String(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["branch_id"],
            ["branches.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_manuscript_blocks_branch_id"), "manuscript_blocks", ["branch_id"], unique=False
    )
    op.create_table(
        "proof_plans",
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("conclusion_revision_id", sa.String(), nullable=False),
        sa.Column("gaps", sa.JSON(), nullable=False),
        sa.Column("rule", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["conclusion_revision_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("revision_id"),
    )
    op.create_index(
        op.f("ix_proof_plans_conclusion_revision_id"),
        "proof_plans",
        ["conclusion_revision_id"],
        unique=False,
    )
    op.create_table(
        "reviews",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("project_id", sa.String(), nullable=False),
        sa.Column("target_revision_id", sa.String(), nullable=False),
        sa.Column("kind", sa.String(), nullable=False),
        sa.Column("verdict", sa.String(), nullable=False),
        sa.Column("coverage", sa.String(), nullable=False),
        sa.Column("scope", sa.Text(), nullable=False),
        sa.Column("findings", sa.JSON(), nullable=False),
        sa.Column("dependency_snapshot", sa.JSON(), nullable=False),
        sa.Column("author", sa.String(), nullable=False),
        sa.Column("created_at", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["projects.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_reviews_project_id"), "reviews", ["project_id"], unique=False)
    op.create_index(
        op.f("ix_reviews_target_revision_id"), "reviews", ["target_revision_id"], unique=False
    )
    op.create_table(
        "revision_parents",
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("parent_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["parent_id"],
            ["revisions.id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("revision_id", "parent_id"),
    )
    op.create_table(
        "dependencies",
        sa.Column("plan_revision_id", sa.String(), nullable=False),
        sa.Column("revision_id", sa.String(), nullable=False),
        sa.Column("role", sa.String(), nullable=False),
        sa.Column("origin", sa.String(), nullable=False),
        sa.Column("scope", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["plan_revision_id"],
            ["proof_plans.revision_id"],
        ),
        sa.ForeignKeyConstraint(
            ["revision_id"],
            ["revisions.id"],
        ),
        sa.PrimaryKeyConstraint("plan_revision_id", "revision_id", "role"),
    )
    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Destructive downgrade is disabled; restore an explicit backup instead.")
